/* audit-all — run every gate in this repository, in order, and assemble the
   Feature Coverage Matrix from what actually ran.

   The matrix is the Master Plan's ledger 1 (2026-09-19 §3), and its rule is
   that "present in code", "looked correct" and "covered indirectly" are not a
   PASS. The only way to keep that true is to refuse to let a row be WRITTEN
   by hand: every row in audit/FEATURE-MATRIX.md is emitted by a check that
   ran, in this process, just now.

   node tools/audit-all.mjs          everything (~12 min)
   node tools/audit-all.mjs --fast   the checks that need no browser
*/
import { spawnSync } from 'node:child_process';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { ROOT } from './harness.mjs';

const FAST = process.argv.includes('--fast');
const SUITES = [
  { file: 'tools/ship-check.mjs', name: 'ship-check — version, #nd, precache, manifest, legacy seal', fast: true },
  { file: 'tools/inventory.mjs', name: 'inventory — the Function Inventory, regenerated', fast: true, quiet: true },
  { file: 'tools/app-check.mjs', name: 'app-check — boot, handlers, panes, views, editor, exports, colour' },
  { file: 'tools/audit-a-shell.mjs', name: 'audit A — shell, startup, corruption recovery, breakpoints', matrix: 'matrix-a.json' },
  { file: 'tools/audit-b-editor.mjs', name: 'audit B — editor ownership, autosave flushing, note lifecycle', matrix: 'matrix-b.json' },
  { file: 'tools/audit-c-org.mjs', name: 'audit C/D — organisation, search, all 11 Smart Views', matrix: 'matrix-c.json' },
  { file: 'tools/audit-e-modules.mjs', name: 'audit E/F — calendar, journal, contacts, database, reminders, review', matrix: 'matrix-e.json' },
  { file: 'tools/audit-g-data.mjs', name: 'audit G/H — export fidelity, import safety, privacy, merge', matrix: 'matrix-g.json' },
  { file: 'tools/audit-i-quality.mjs', name: 'audit I — accessibility, security, privacy, scale, PWA', matrix: 'matrix-i.json' },
  { file: 'audit/repro/journeys.mjs', name: 'journeys — 24 principal journeys, real clicks' },
  { file: 'audit/repro/persistence-reload.mjs', name: 'persistence — what the app writes survives a real reload' },
  { file: 'audit/repro/note-wipe-real-clicks.mjs', name: 'repro — Finding 1, the note-wipe, at three sizes', noCount: true },
  { file: 'audit/repro/export-residue.mjs', name: 'repro — Finding 2, private residue in both exports', noCount: true },
];

const results = [];
for (const s of SUITES) {
  if (FAST && !s.fast) continue;
  process.stdout.write(`\n▶ ${s.name}\n`);
  const t0 = Date.now();
  const run = spawnSync(process.execPath, [join(ROOT, s.file)], { cwd: ROOT, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
  const out = (run.stdout || '') + (run.stderr || '');
  if (!s.quiet) process.stdout.write(out.split('\n').filter((l) => /^ FAIL|passed|VERDICT|EXPORT|^\s{2}"/.test(l)).join('\n') + '\n');
  const tally = (out.match(/(\d+)\/(\d+) passed/g) || []).pop();
  const [pass, total] = tally ? tally.match(/(\d+)\/(\d+)/).slice(1).map(Number) : [null, null];
  results.push({ ...s, code: run.status, pass, total, ms: Date.now() - t0,
    fails: (out.match(/^ FAIL .*/gm) || []) });
}

/* ── assemble the matrix ─────────────────────────────────────────────────── */
const rows = [];
for (const s of SUITES) {
  if (!s.matrix) continue;
  const f = join(ROOT, 'audit', 'inventory', s.matrix);
  if (existsSync(f)) rows.push(...JSON.parse(readFileSync(f, 'utf8')));
}
const byStatus = rows.reduce((a, r) => (a[r.status] = (a[r.status] || 0) + 1, a), {});
const byDomain = {};
for (const r of rows) (byDomain[r.domain] ||= []).push(r);

const esc = (s) => String(s).replace(/\|/g, '\\|').replace(/\n/g, ' · ');
const inv = existsSync(join(ROOT, 'audit/inventory/summary.json'))
  ? JSON.parse(readFileSync(join(ROOT, 'audit/inventory/summary.json'), 'utf8')) : {};
const version = (readFileSync(join(ROOT, 'index.html'), 'utf8').match(/name="app-version" content="([\d.]+)"/) || [])[1];

let md = `# Siyagah — Feature Coverage Matrix

*Generated by \`node tools/audit-all.mjs\`. Every row below was emitted by a
check that ran; none of them can be written by hand. "Present in code",
"looked correct" and "covered indirectly" are not a PASS — Master Plan
2026-09-19 §3.*

| | |
|---|---|
| App version | v${version} |
| Generated | ${new Date().toISOString().slice(0, 16).replace('T', ' ')} UTC |
| Matrix rows | **${rows.length}** |
${Object.entries(byStatus).map(([k, v]) => `| ${k} | ${v} |`).join('\n')}

## Every gate in this repository

| Suite | Result | Time |
|---|---|---:|
${results.map((r) => `| ${esc(r.name)} | ${r.code === 0 ? (r.total ? `**${r.pass}/${r.total}**` : '**pass**') : `**FAILED**${r.total ? ` (${r.pass}/${r.total})` : ''}`} | ${(r.ms / 1000).toFixed(1)}s |`).join('\n')}

**Total checks: ${results.reduce((n, r) => n + (r.total || 0), 0)}** across ${results.length} suites.
${results.some((r) => r.code !== 0) ? '\n> **Some suites FAILED.** See the failing rows below.\n' : ''}
`;

for (const [dom, rs] of Object.entries(byDomain)) {
  md += `\n## ${dom}\n\n| Feature | Viewport | Status | Evidence |\n|---|---|---|---|\n`;
  for (const r of rs) md += `| ${esc(r.feature)} | ${r.viewport} | ${r.status === 'PASS' ? 'PASS' : `**${r.status}**`} | ${esc(r.detail).slice(0, 180)} |\n`;
}

md += `\n## Function Inventory\n\n`;
md += `Generated mechanically from \`index.html\` — see \`audit/inventory/FUNCTION-INVENTORY.md\`.\n\n`;
md += Object.entries({
  'Application-defined functions': inv.functions, 'Reachable': inv.reachable,
  'Referenced nowhere at all': (inv.unreferenced || []).length,
  'That mutate the data model': inv.mutateModel, 'That reach a persistence boundary': inv.persist,
  'Classified destructive': inv.destructive, 'Privacy-sensitive': inv.privacySensitive,
  'That touch the network': inv.network, 'Inline on* handlers in markup': inv.inlineHandlers,
}).map(([k, v]) => `- **${k}:** ${v ?? '—'}`).join('\n') + '\n';

writeFileSync(join(ROOT, 'audit', 'FEATURE-MATRIX.md'), md);
writeFileSync(join(ROOT, 'audit', 'inventory', 'matrix.json'), JSON.stringify(rows, null, 1));

const failed = results.filter((r) => r.code !== 0);
console.log('\n' + '='.repeat(64));
console.log(`${results.reduce((n, r) => n + (r.total || 0), 0)} checks across ${results.length} suites · ${rows.length} matrix rows`);
console.log(Object.entries(byStatus).map(([k, v]) => `${k}: ${v}`).join(' · '));
console.log(failed.length ? `\nFAILED SUITES: ${failed.map((f) => f.file).join(', ')}` : '\nAll suites green.');
console.log('audit/FEATURE-MATRIX.md written.');
process.exit(failed.length ? 1 : 0);
